import Link from "next/link";
import { useEffect, useState } from "react";

const Navbar = () => {

	return (
		/* Navbar - some styling in this page is generated by chatgpt */
		<header
			className="sticky top-0 z-50"
			style={{
				backgroundColor: "var(--background)",
				color: "var(--foreground)",
			}}
		>
			<div className="container mx-auto px-6 py-4 flex flex-wrap items-center justify-between">
				<h1
					className="text-4xl font-extrabold"
					style={{ color: "var(--foreground)" }}
				>
					Scriptorium
				</h1>

				{/* Navigation */}
				<nav className="w-full mt-4 md:mt-0 md:w-auto flex flex-col md:flex-row md:space-x-6 space-y-4 md:space-y-0 items-left">
					<Link
						href="/"
						className="font-medium transition-colors hover:text-[var(--accent-color)] text-[var(--foreground)] duration-200"
					>
						Home
					</Link>
					<Link
						href="/templates"
						className="font-medium transition-colors hover:text-[var(--accent-color)] text-[var(--foreground)] duration-200"
					>
						Templates
					</Link>
					<Link
						href="/blogs"
						className="font-medium transition-colors duration-200 hover:text-[var(--accent-color)] text-[var(--foreground)]"
					>
						Blog Posts
					</Link>
					<Link
						href="/#code-execution"
						className="font-medium transition-colors duration-200 hover:text-[var(--accent-color)] text-[var(--foreground)] scroll-smooth"
					>
						Editor
					</Link>
						<Link
							href="/profile"
							className="font-medium transition-colors duration-200 hover:text-[var(--accent-color)] text-[var(--foreground)]"
						>
							Profile
						</Link>
						<Link
							href="/login"
							className="font-medium transition-colors duration-200 hover:text-[var(--accent-color)] text-[var(--foreground)]"
						>
							Login
						</Link>
				</nav>
			</div>
		</header>
	);
};

export default Navbar;
